# Generated by Django 5.1.6 on 2025-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypost',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
