# Generated by Django 5.1.6 on 2025-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_companypost_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypost',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
