# Generated by Django 5.1.6 on 2025-02-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_companypost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypost',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companypost',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companypost',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
