# Generated by Django 5.1.6 on 2025-02-08 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Company')]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
