# Generated by Django 5.1.6 on 2025-02-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_companyname_companyaccount_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaccount',
            options={'permissions': [('create_post', 'can create post')]},
        ),
    ]
